### PR TITLE
dashboard-Impl

### PR DESCRIPTION
**Pull request by timibacco**

### CODE REVIEW

**Comment by timibacco** [comment]
token, now required to access the controllers that don't have emails in their dtos

**Comment by nxghub** [comment]
Your PR is still having Merge Conflicts. Kindly resolve this and make another PR.

**Comment by timibacco** [comment]
> Your PR is still having Merge Conflicts. Kindly resolve this and make another PR.

I don't think I can. The main is broken.  I would only be able to pull when corrected.

**Comment by nxghub** [comment]
Please, try to run the main on your local. Make sure it works, then merge into your branch locally, push and make a PR on your branch.

**Pull request closed without merging**
