### PR TITLE
Email verify working

### PR DESCRIPTION
**Pull request by timibacco**

### CODE REVIEW

**Comment by nxghub** [comment]
Please, call the mail service before persisting a user to the database.

**Comment by timibacco** [comment]
> Please, call the mail service before persisting a user to the database.

Ok, but that would strike out the need for the controller, hence the choice for users to choose one of any of  the verification methods. Am I right?

Cc: Figma file

**Comment by nxghub** [comment]
You dont need a mailservice controller. The create account controller suffices. pass the token as part of the message body the user creating account will receive. This is just to confirm the email is valid. If the token is not received, then the user cannot be persisted.

**Comment by timibacco** [comment]
Okay. 
Also can we also get a sample otp sender for phone. Thanks.

**Pull request closed without merging**
